#!/usr/bin/env python3
"""
Helper script to ensure .fellow-data/ is in target project's .gitignore
"""

import os
from pathlib import Path
from typing import Optional


def ensure_gitignore_entry(project_path: Path) -> bool:
    """
    Ensure .fellow-data/ is in the project's .gitignore file.

    Args:
        project_path: Path to the target project

    Returns:
        True if entry was added or already exists, False on error
    """
    gitignore_path = project_path / '.gitignore'

    fellow_entry = '.fellow-data/'
    comment_block = '''
# Fellow - Knowledge Base and Logs
# Generated by Fellow plugin - do not commit
.fellow-data/
'''

    try:
        # Check if .gitignore exists
        if gitignore_path.exists():
            # Read existing content
            with open(gitignore_path, 'r') as f:
                content = f.read()

            # Check if entry already exists
            if fellow_entry in content:
                return True  # Already present

            # Append the entry
            with open(gitignore_path, 'a') as f:
                # Add newline if file doesn't end with one
                if content and not content.endswith('\n'):
                    f.write('\n')
                f.write(comment_block)

            return True

        else:
            # Create new .gitignore with Fellow entry
            with open(gitignore_path, 'w') as f:
                f.write(comment_block.lstrip())

            return True

    except Exception as e:
        print(f"Warning: Could not update .gitignore: {e}", file=sys.stderr)
        return False


def should_add_gitignore_entry(project_path: Path) -> bool:
    """
    Check if we should add .gitignore entry.

    Only add if:
    - Project is a git repository
    - .fellow-data/ exists
    """
    # Check if it's a git repo
    git_dir = project_path / '.git'
    if not git_dir.exists():
        return False

    # Check if .fellow-data/ exists
    fellow_data = project_path / '.fellow-data'
    if not fellow_data.exists():
        return False

    return True


if __name__ == '__main__':
    import sys

    if len(sys.argv) < 2:
        print("Usage: python3 gitignore_helper.py <project_path>")
        sys.exit(1)

    project_path = Path(sys.argv[1])

    if not project_path.exists():
        print(f"Error: Project path does not exist: {project_path}")
        sys.exit(1)

    if should_add_gitignore_entry(project_path):
        if ensure_gitignore_entry(project_path):
            print(f"✓ Added .fellow-data/ to {project_path}/.gitignore")
        else:
            print(f"✗ Failed to update .gitignore")
            sys.exit(1)
    else:
        if not (project_path / '.git').exists():
            print("ℹ️  Not a git repository - skipping .gitignore update")
        else:
            print("ℹ️  .fellow-data/ not found - skipping .gitignore update")
